[[mgr.prepend_keymap]]
on   = "<A-Left>"
run  = "back"
desc = "Back to previous directory"

[[mgr.prepend_keymap]]
on   = "<A-Right>"
run  = "forward"
desc = "Forward to next directory"

[[mgr.prepend_keymap]]
on   = "<A-Up>"
run  = "seek -2"
desc = "Seek up 5 units in the preview"

[[mgr.prepend_keymap]]
on   = "<A-Down>"
run  = "seek 2"
desc = "Seek down 5 units in the preview"

[[mgr.prepend_keymap]]
on   = "y"
run  = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
desc = "Yank selected files"

[[mgr.prepend_keymap]]
on   = "<C-n>"
run  = 'shell -- dragon-drop -x -i -T "$0"'
desc = "Drag and drop files"
