[mgr]
show_hidden = true

[opener]
default = [
  { run = 'xdg-open "$@"', orphan = true, desc = "Open with default app" },
]

[open]
rules = [
  { mime = "image/*", use = "default" },
  { mime = "video/*", use = "default" },
]
