[general]
# Exit directly after copy/save action
early-exit = true
corner-roundness = 6
# Select the tool on startup [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "rectangle"
